{{/*
#
# SPDX-License-Identifier: Apache-2.0
#
*/}}

{{- define "fmRestApiLivenessProbeTemplate" }}
tcpSocket:
  port: {{ tuple "faultmanagement" "internal" "api" . | include "helm-toolkit.endpoints.endpoint_port_lookup" }}
{{- end }}

{{- if .Values.manifests.deployment_fm_rest_api }}
{{- $envAll := . }}

{{- $mounts_fm_rest_api := .Values.pod.mounts.fm_rest_api.fm_rest_api }}
{{- $mounts_fm_rest_api_init := .Values.pod.mounts.fm_rest_api.init_container }}

{{- $serviceAccountName := "fm" }}
{{ tuple $envAll "fmapi" $serviceAccountName | include "helm-toolkit.snippets.kubernetes_pod_rbac_serviceaccount" }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fm-rest-api
  labels:
{{ tuple $envAll "fm" "fmapi" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 4 }}
spec:
  replicas: {{ .Values.pod.replicas.api }}
  selector:
    matchLabels:
{{ tuple $envAll "fm" "fmapi" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 6 }}
{{ tuple $envAll | include "helm-toolkit.snippets.kubernetes_upgrades_deployment" | indent 2 }}
  template:
    metadata:
      labels:
{{ tuple $envAll "fm" "fmapi" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 8 }}
    spec:
      serviceAccountName: {{ $serviceAccountName }}
      initContainers:
{{ tuple $envAll "fmapi" $mounts_fm_rest_api_init | include "helm-toolkit.snippets.kubernetes_entrypoint_init_container" | indent 8 }}
      containers:
        - name: fm-rest-api
{{ tuple $envAll $envAll.Values.pod.resources.fm | include "helm-toolkit.snippets.kubernetes_resources" | indent 10 }}
          env:
            - name: RUNNING_IN_CONTAINER
              value: "True"
          volumeMounts:
            - name: fm-bin
              mountPath: /tmp/fm-rest-api.sh
              subPath: fm-rest-api.sh
              readOnly: true
            - name: fm-etc
              mountPath: /etc/fm/api-paste.ini
              subPath: api-paste.ini
              readOnly: true
            - name: fm-etc
              mountPath: /etc/fm/fm.conf
              subPath: fm.conf
              readOnly: true
            - name: fm-etc
              mountPath: /etc/fm/logging.conf
              subPath: logging.conf
              readOnly: true
            - name: fm-etc-event
              mountPath: /etc/fm/events.yaml
              readOnly: true
              #faultmanagement
{{- dict "enabled" .Values.manifests.certificates "name" .Values.secrets.tls.faultmanagement.fm_api.public | include "helm-toolkit.snippets.tls_volume_mount" | indent 12 }}
{{ dict "envAll" . "component" "fm_rest_api" "container" "default" "type" "liveness" "probeTemplate" (include "fmRestApiLivenessProbeTemplate" . | fromYaml) | include "helm-toolkit.snippets.kubernetes_probe" | indent 10 }}
          command:
            - /tmp/fm-rest-api.sh
          image: "{{ .Values.images.tags.fm_rest_api }}"
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          ports:
            - name: http
              containerPort: 18003
              protocol: TCP
      nodeSelector:
        {{ .Values.labels.fm_api.node_selector_key }}: {{ .Values.labels.fm_api.node_selector_value }}
{{ if $envAll.Values.pod.tolerations.fm.enabled }}
{{ tuple $envAll "fm" | include "helm-toolkit.snippets.kubernetes_tolerations" | indent 6 }}
{{ end }}
      affinity:
        {{ tuple $envAll "fm" "fmapi" | include "helm-toolkit.snippets.kubernetes_pod_anti_affinity" | indent 8 }}
    {{- with .Values.tolerations }}
    {{- end }}
      volumes:
        - name: fm-etc
          secret:
            secretName: fm-etc
            defaultMode: 0644
        - name: fm-bin
          configMap:
            name: fm-bin
            defaultMode: 0755
        - name: fm-etc-event
          hostPath:
            path: /etc/fm/events.yaml
            type: File
{{- dict "enabled" .Values.manifests.certificates "name" .Values.secrets.tls.faultmanagement.fm_api.public | include "helm-toolkit.snippets.tls_volume" | indent 8 }}
{{- end }}
