---
- project:
    check:
      jobs:
        - starlingx-common-tox-linters
    gate:
      jobs:
        - starlingx-common-tox-linters
    post:
      jobs:
        - stx-helm-charts-upload-git-mirror

- job:
    name: stx-helm-charts-upload-git-mirror
    parent: upload-git-mirror
    description: >
      Mirrors opendev.org/starlingx/helm-charts to
      github.com/starlingx/helm-charts
    vars:
      git_mirror_repository: starlingx/helm-charts
    secrets:
      - name: git_mirror_credentials
        secret: stx-helm-charts-github-secret3
        pass-to-parent: true

- secret:
    name: stx-helm-charts-github-secret3
    data:
      user: git
      host: github.com
      # yamllint disable-line rule:line-length
      host_key: github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=
      ssh_key: !encrypted/pkcs1-oaep
        - IK4zyI5L3W2V55c+OhAu30WygmQHMmpu3M0icsVziXyat4CdaKvOYTYy6MBhYiOa2vx9t
          geiXQwvOMxLzL1WYSezvhP+yjLamgZWEYtiAyN8zy2ktOksXgt95qUrDmyGF5f06MUmXt
          8Xlz5XwmNyIGoYJT56duQSzlo0GSZczzplXA+inO3JZwXxU4c9/8P9CoY6wUtqINPK7Zr
          59lsk1eISUOJ9KNHS9HefLIDczmUcVGzeNZ7TK9mC53KUwS8InKXZzBPCNuicAFsw62m/
          6hzIndhzaUK1rbE3xHq0p3Z3PmYB0QkotMl1mpHt1zfSsLHFhQPOMQIj20T00/uGXVvbi
          EsJhHMgNBtW7778045RCOiB91x5krJ/IOmJlBlLjrNpB/QcxutRdM11lRz9lrL0cf/p4N
          iNuvx19nPt080bTo6P6L6z4TNDoWBksBQViLQBKrdGMSQFRCJvvM8dOhZWazqg5QoW3Is
          iYkQ899dfYzS2uryfD35pTItBrFwRCUI3V3KcTU8BsTjUBIR+msbLuXhm9eYNhNhjzwBv
          Pb8zZQ2izESjT8c9ot0ZygHu5znHWfFXtQb0b0n6n+3jOYxNw8q7ly8AGtFEIYc4xd85K
          vXrdXGqB+Nw7l3+tFg1IAeDisdosGQqifyb/Yta87uZKNnZDbj40zWa2VDUUeM=
        - cCWms/PGGoN6gPDusqA9wzxWbdsXhjQxCz+FMVkehYfa6a9OtGU65rvmL60P1XyjlFskM
          uieJk9qyvNNAHxgnAD44glwroKrWjXJ8zGkje/t8x4iOJhueBm2FE1bQVvakCCjZ5QfCL
          KzgahiVvZ9mBD0rxaHWT8xGxzWHvP6MJ054t7ij/AjCFGJzcz/nTcYcT+EJcsz03jBtwV
          iZIPlNN1xrQ2w3FKCbsSchb3ssa2uA1yqoujzymEGFj2HLXY0KqdFTuAn70iSoHLCf8d1
          ZCF4OVypBzBkMJKJgmojwVxzMfiy7YY3wjKldl3vg6PmlklaGwdVidcFVwgr18LmpkF2L
          WoBTKyrpmqiyj1V20LWcS8ywHmtmCqMETnXHAxWbKFuVi9L9d7qUwJ9NGW6+aChMaYXxF
          P970+AgI5CLVV6BOMqM9xYcxiyZq/XgQFxioOLv92lV3cExGv8hHyShRyq78AFnV+a357
          hsYQ4Wr6UXeu1REb90Bt8ezHP+pdH8FxOJoz/EeXTUf/pd853zr7M8uq356LBlrThENzA
          79oVnEQv5JGi6ocH95I6eSwZwuMxHHm/l+xv9EdWMBJ/ylN+AcdnhvGRz/RjWY7CA+y8d
          8TIyctyqH4zjXKsYrCURTZxWG+JyOGch5eCfm8otXa8oYXfg6fldfkplu1Dbuo=
        - MwaMWJqlEFo3iXhHdFUxarmXCxWi1+bEa+daJ5upjxL6wWu2MTrRtlwyqAyoi646kgKuC
          UcWKt7IpfNAmFminpX//4NyghFrqCgmUomj2HHgecY7+6P6bNAM0+BScvphkeRtVDtJdt
          H0QaAmS6gUqZVukDFQ29U2XgHh9/1kNd3cQj/6v+QBfQn9Bhmonts70HE84kg+SQtDec1
          Z8Kpkxk/jnwX31Q5pwRtpZwSaij25G1Jqu0XwkAJq56ulgurEEKvOgQVFAz3oVJM/pvzR
          oFAelAU7Rhydzhl3rsWw0w37S/F/nKOgpIBJMJd75VsytO1DcKp4VOCAKGCzpkpTMwvdW
          4MYYVZQNhJsb50o3K8MmnVbS7hxoBigv9DQBQpKPxCBQZVYTQwKwZAyPRpibOCFzUkcJD
          tB4Ww6KziPhC/qjlF3vChA0nKJwJQAJQ3byfTjioRaXv40ca9xMESf8mECJynoSftmPR9
          03x70nYfbYV5O8c6WmUYd3zuWw+FxmJpVItTGXXFc5NK4vxuyv7plB5msW+gV9XAYlieh
          njV1TdKIK83TybdBbkhmSNvwgjYkvQbucATpQTkhQwC6r/ArEve6XAtaPCSVhC/+Xo2Ih
          0IG9dAk1P2ZWsTuejnWgNiE/oR9/x5O8nxJJmuXKIwbXSSKKkP22QI43BorUbE=
        - JjLj2k/GBOzbvgAxW8oizzCFicDf6BSXhUdg5BRKrAJTCeZf5GqbBK702H6lSMHMz69hB
          5rVE4UFlgH+IjjaFp7NvZd3OzxHBJiDtEOa1qPk5C6AE5/TcqhCA/I7rwzo7BCdc1X4PO
          fQhB1jXtRNnaYsUoSIMNXpSoZmFQicDNdJX3U64pdoeQNO1zbCCS99n3CsBXYCf95/8VI
          9V2L0e31z7qLkexioogc2Lp6rsegMlAOY5XxQ7wrGs82RZFWXIvfPPn5xTZPGyDEpD8MX
          8Ibih8fTcJLHFj5YmDcO+HWoJUwbbB5bYPJcqm0eKMDL+PD2McBoQffFGmRr0XVjr3KXG
          iDhpi2GhVwl6qHNT0xvzcO6WG2TdYfTQgrEUnjNMzn61WGwU7eg/6YNdgOn9Cnkla+EBR
          IqzY4/ufuiwZIrR79nHYk4pZpJVFIPm8C1st4ztoezm4cZ0L2/gBAwgzWX8tJhV7DYY0r
          G82ATofx02IogzkAYEtf6MBXNZIskxm5yNSwFpNSHpmz+vP8SbDMtwdjdozt329duz5Ej
          2owzFsZxaoUrLNl3C13PF5nZNkhJmT92jAzP8BIAu7Ucmimqk1zBEE+WmkjcGSqywWsJj
          iCHu3Rz1et+TBMhFUL9BZKIQCiZYG7LKBAwNjMTgjJE4INhS73HYs12UHOodbg=
        - RIF0kcQViSDvUCNFNZlpz30VBL/+nDj3thvjpxJ3XehuyBfWUHBC6l21j/pZ+5IoQV8pa
          tBGOQspND8UpnOFYMlqJvsV3GU4j7xglfZRlM1uzt1qCMgZVthTNIEjr3Rx8ND9Tb/uG4
          EtboYGVhrdSfEltDZYUPG4AHK5nyVcOlbwlMz5yv5WcsTLvOyE4Juqmg1ve/OEj0q1nSL
          PBnlIApUKvBDadS/G7X43qdPtqq+IPmwFt4jmRvi4CTGAU/vxRf+QmDu9jHItwriVRsnw
          SEILTrn2ddlLNEeL5VXuDO5Y4E8gcZGWB1p+ZCHnKevWM2c1oRuzWtKm4Wd7nb2sYbnuI
          kfM4HcLLvvVn+D3Nps/5Q3byrMXo1UqtHSOjkAZIl278rfxVwYeCzJzkT0qRKeq9jIG24
          L/m/f1JA4eGVbRSGUH+bCMnkIiBwrxSwWMjJW08JqduufC29JE6megUfnP13SpIqy7Rih
          xxnYymhB+VLt3Wu8SHW/gWwUmNIGH8KWYzP2jEAOjArDE5l7ZJXImtSPg08zDUFCs06EA
          jniDRjBKGwfvKizK3uonCBxUtaVTowKrESIJEEs9tssC8NWgDovx4Zf2UNuzlQX/cCQO2
          9QmNMS7LTi1TdB+4LebT3EaIaQLV4qXoNtCJiInMfkeiCvzpDcoq/N0rfOsUo0=
        - BRwDArmHnwqzFflfM9jiIW7b3ifHfvIxTaigXNUvqW3pIBrj6Y+QabjNASXpDi3CZhodN
          8aXzI2rgoObPmltZr7FRrqWo6JBigVBRnnFQA1iNyxKli2q4w0Hf/c6Pm8JR8McWeDoVi
          LctKft2996b1qZipu/CCzaDPBhbqsoXcGQNrH+YpXcZR1M4LdBiqPZDQAxQlSG2BWRMwI
          J1yCjG/XP9Wba6Y5xe6bYcAwFp0LN6Kjsr4nA3c6eEKLjm+XJ6EPo4NDTYtvztzkSfmZ9
          Jrx+yV3mYoF19NP/auXN/ofYgXaFrqSs+vGqNKPdlqGJPuFNnYiRX1l8tDZkWQYlB1n1o
          52PuYBXKqgf4qnILqzv7qixCSWPtHF6j40vJ3D5GD1H5wXkwXbvVGdZZULRpbpKY1nDgx
          uFEkpTNWdWcdixuMefpKg5S7srzc9mDcyNzffaQAxFDB/s7HjzWyu8HalnpsVuDblv4wU
          xjFqg8GVKlNBEgVKyHBp43gBqMJdjxBROpNXxr82yAeCuK/V26+iZozSa5bTQ6bQekwqZ
          /uX1E2SqM94pvlu0qGUWvdh9hrn9nQ2DWDLlLiPlgBV4yTVpFy1hrS+42o5k/G/jPY5m/
          tMvOV8lHYQQbwHqbUAhXT/6/5GDOoV8DT/K1NAIVjooFGK8ex/8z5bNepOgYuQ=
        - HmubzuSxijN4/Hvmkkni+9CQm1CEsJGBReAofgUMXWZbm6qW5Uiq3LQ/c34/TYS0WPJD1
          ejtW52RC9vwZL0sLONDshzf+ChCuvMEGsm1DERjmLqUIuJpwAlNMoPSVLCZm7Y8zKG7UR
          TGRY4SVId+oVtM0aciRFu5RJ0V/QaFtCgbvdCQpKRkf76IiFQPZY0Pc+BlnPSbItzITkl
          pNoxt4AzAde9+alrmK+qB1UFxz7aaVwh6RLI/J3r4xKBBMeKk2OsGOxoO36iwHFhTDCdr
          ga4GC1uYuQ6CgO/t13vQWd35xJCt0a940+/d4G/WOqt017+UjHGWia3gwErSTV3kwHx98
          aNWrk35TdEBRTrx+52H8GlhnjdXJ6Y+CZrOKtsWjfHckNIIFKJhDqWzCiif8gR/0SeIMq
          phTgyom/7zkLPawiUdMQG29Zg7rs9cMvkwjFF3QII3GPJqwE12YDnKykFRGke7oxK0R6R
          ad+sQMDVvJLK26GQbLCZzbpZOD/9s0mJBvBuSOjeFVNGzm9owYzvq581vjEc1B2vnbzSH
          Qjwtlu+Db0wSbDVpyxc4+XZLvFG3+RGbNmKL1nG2PcLp7NsfEJdYVMqhhPjR4qIRDAPqF
          qH7xa+lX9lqVU1TFCtQSY6xZ4kahBIB2/lQ83J+DIiUrCZCco07OFSsyaKgTgE=
