{{/*
#
# Copyright (c) 2021 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
*/}}

{{- if .Values.clusterRoleBinding.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    release: "{{ .Release.Name }}"
  name: secret-observer-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: secret-observer-cr
subjects:
- kind: ServiceAccount
  name: secret-observer
  namespace: {{ .Values.namespace }}
{{- end -}}
