{{/*
#
# Copyright (c) 2021-2022 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
*/}}

{{- if .Values.clusterRole.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secret-observer-cr
  labels:
    app: secret-observer
    release: "{{ .Release.Name }}"
rules:
  - apiGroups: ["apps"]
    resources:
      - deployments
    verbs:
      - patch
{{- end -}}
