{{/*
#
# Copyright (c) 2021-2024 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
*/}}

{{- if .Values.RoleBinding.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: "{{ .Values.namespace }}"
  labels:
    release: "{{ .Release.Name }}"
  name: secret-observer-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secret-observer-r
subjects:
- kind: ServiceAccount
  name: secret-observer
  namespace: {{ .Values.namespace }}
{{- end -}}
