{{/*
#
# Copyright (c) 2021-2024 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
*/}}

{{- if .Values.Role.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: "{{ .Values.namespace }}"
  name: secret-observer-r
  labels:
    app: secret-observer
    release: "{{ .Release.Name }}"
rules:
  - apiGroups: ["apps"]
    resources:
      - deployments
    verbs:
      - patch
{{- end -}}
